#!/bin/bash
# Automated release script for claude-kan
# Bumps version (patch), builds, commits, tags, and publishes to npm

set -e  # Exit on any error

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
CYAN='\033[0;36m'
NC='\033[0m' # No Color

# Parse arguments
VERSION_BUMP=${1:-patch}  # Default to patch, accept major/minor/patch
DRY_RUN=${2:-false}        # Dry run mode (no actual publish)

echo -e "${CYAN}================================${NC}"
echo -e "${CYAN}🚀 Claude-Kan Release Script${NC}"
echo -e "${CYAN}================================${NC}"
echo -e "${CYAN}Version bump: $VERSION_BUMP${NC}"
if [ "$DRY_RUN" = "--dry-run" ]; then
  echo -e "${YELLOW}⚠️  DRY RUN MODE (no actual publish)${NC}"
fi
echo ""

# Step 1: Run verification
echo -e "${BLUE}[Step 1/9] Running pre-release verification...${NC}"
if ! ./scripts/verify-release.sh; then
  echo -e "${RED}❌ Verification failed. Please fix issues before releasing.${NC}"
  exit 1
fi
echo -e "${GREEN}✅ Verification passed${NC}"
echo ""

# Step 2: Check for uncommitted changes
echo -e "${BLUE}[Step 2/9] Checking for uncommitted changes...${NC}"
if [ -n "$(git status --porcelain)" ]; then
  echo -e "${YELLOW}⚠️  You have uncommitted changes.${NC}"
  echo ""
  git status --short
  echo ""
  read -p "Do you want to commit these changes? (y/n) " -n 1 -r
  echo ""
  if [[ $REPLY =~ ^[Yy]$ ]]; then
    echo -e "${BLUE}Please enter a commit message:${NC}"
    read COMMIT_MESSAGE

    git add .
    git commit -m "$COMMIT_MESSAGE"
    echo -e "${GREEN}✅ Changes committed${NC}"
  else
    echo -e "${YELLOW}⚠️  Proceeding with uncommitted changes (not recommended)${NC}"
  fi
else
  echo -e "${GREEN}✅ Working directory is clean${NC}"
fi
echo ""

# Step 3: Get current version
echo -e "${BLUE}[Step 3/9] Getting current version...${NC}"
CURRENT_VERSION=$(node -p "require('./package.json').version")
echo -e "${CYAN}Current version: $CURRENT_VERSION${NC}"
echo ""

# Step 4: Bump version
echo -e "${BLUE}[Step 4/9] Bumping version ($VERSION_BUMP)...${NC}"
if [ "$DRY_RUN" = "--dry-run" ]; then
  NEW_VERSION=$(npm version $VERSION_BUMP --no-git-tag-version --json | node -p "JSON.parse(require('fs').readFileSync('/dev/stdin')).['claude-kan']")
  echo -e "${YELLOW}[DRY RUN] Would bump to: $NEW_VERSION${NC}"
  # Revert version bump in dry run
  git checkout package.json package-lock.json 2>/dev/null || true
else
  NEW_VERSION=$(npm version $VERSION_BUMP --no-git-tag-version)
  echo -e "${GREEN}✅ Version bumped to: $NEW_VERSION${NC}"
fi
echo ""

# Step 5: Update version in files (if needed)
echo -e "${BLUE}[Step 5/9] Building project...${NC}"
if npm run build; then
  echo -e "${GREEN}✅ Build successful${NC}"
else
  echo -e "${RED}❌ Build failed${NC}"
  exit 1
fi
echo ""

# Step 6: Run tests (if they exist)
echo -e "${BLUE}[Step 6/9] Running tests...${NC}"
if [ -d "test" ] || [ -d "tests" ]; then
  if npm test; then
    echo -e "${GREEN}✅ Tests passed${NC}"
  else
    echo -e "${RED}❌ Tests failed${NC}"
    exit 1
  fi
else
  echo -e "${YELLOW}⚠️  No tests found (skipping)${NC}"
fi
echo ""

# Step 7: Commit version bump
echo -e "${BLUE}[Step 7/9] Committing version bump...${NC}"
if [ "$DRY_RUN" = "--dry-run" ]; then
  echo -e "${YELLOW}[DRY RUN] Would commit version bump${NC}"
else
  git add package.json package-lock.json
  git commit -m "Release v$NEW_VERSION

- Bump version to $NEW_VERSION
- Auto-generated by release script"

  # Create git tag
  git tag -a "v$NEW_VERSION" -m "Release v$NEW_VERSION"
  echo -e "${GREEN}✅ Committed and tagged: v$NEW_VERSION${NC}"
fi
echo ""

# Step 8: Publish to npm
echo -e "${BLUE}[Step 8/9] Publishing to npm...${NC}"
if [ "$DRY_RUN" = "--dry-run" ]; then
  echo -e "${YELLOW}[DRY RUN] Would run: npm publish --access public${NC}"
  npm pack --dry-run
else
  # Check if logged in to npm
  if npm whoami &>/dev/null; then
    echo -e "${CYAN}Publishing as: $(npm whoami)${NC}"

    # Publish
    if npm publish --access public; then
      echo -e "${GREEN}✅ Published to npm successfully!${NC}"
    else
      echo -e "${RED}❌ npm publish failed${NC}"
      echo -e "${YELLOW}⚠️  Version was committed and tagged. You may need to:${NC}"
      echo -e "${YELLOW}   1. Fix the issue${NC}"
      echo -e "${YELLOW}   2. Manually run: npm publish --access public${NC}"
      exit 1
    fi
  else
    echo -e "${RED}❌ Not logged in to npm${NC}"
    echo -e "${YELLOW}Please run: npm login${NC}"
    exit 1
  fi
fi
echo ""

# Step 9: Push to GitHub
echo -e "${BLUE}[Step 9/9] Pushing to GitHub...${NC}"
if [ "$DRY_RUN" = "--dry-run" ]; then
  echo -e "${YELLOW}[DRY RUN] Would push commits and tags to origin${NC}"
else
  if git remote | grep -q origin; then
    git push origin main || git push origin master
    git push origin --tags
    echo -e "${GREEN}✅ Pushed to GitHub${NC}"
  else
    echo -e "${YELLOW}⚠️  No git remote 'origin' configured (skipping push)${NC}"
  fi
fi
echo ""

# Success summary
echo -e "${CYAN}================================${NC}"
echo -e "${CYAN}🎉 Release Complete!${NC}"
echo -e "${CYAN}================================${NC}"
echo ""
echo -e "${GREEN}Released version: $NEW_VERSION${NC}"
echo ""
echo -e "${CYAN}Next steps:${NC}"
if [ "$DRY_RUN" != "--dry-run" ]; then
  echo -e "  1. View on npm: ${YELLOW}https://www.npmjs.com/package/claude-kan${NC}"
  echo -e "  2. Test installation: ${YELLOW}npx claude-kan@$NEW_VERSION init${NC}"
  echo -e "  3. Create GitHub release: ${YELLOW}https://github.com/sudiptosen/claude-kan/releases/new${NC}"
else
  echo -e "  1. Review the dry run output above"
  echo -e "  2. Run without --dry-run to actually release: ${YELLOW}npm run release${NC}"
fi
echo ""
echo -e "${GREEN}✨ Done!${NC}"
